<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Persistence\Migrations\" />
      <Folder Include="Persistence\Options\Postgres\" />
      <Folder Include="Persistence\Repositories\Postgres\" />
    </ItemGroup>

</Project>
