<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentMigrator" />
      <PackageReference Include="FluentMigrator.Extensions.Postgres" />
      <PackageReference Include="FluentMigrator.Runner" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Hosting" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
      <PackageReference Include="Npgsql" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Application\UserService.Application.Abstractions\UserService.Application.Abstractions.csproj" />
    </ItemGroup>

</Project>
