<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <Content Update="appsettings.*.json">
            <DependentUpon>appsettings.json</DependentUpon>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Application\UserService.Application\UserService.Application.csproj" />
      <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
      <ProjectReference Include="..\Presentation\Grpc\Grpc.csproj" />
    </ItemGroup>

</Project>